/**
 * Embedded default seccomp profile.
 *
 * This keeps strict seccomp available in standalone compiled binaries where
 * docker/seccomp-profile.json may not be present on disk.
 */
export const EMBEDDED_DEFAULT_SECCOMP_PROFILE = JSON.stringify({
  defaultAction: "SCMP_ACT_ALLOW",
  architectures: ["SCMP_ARCH_X86_64", "SCMP_ARCH_X86", "SCMP_ARCH_X32", "SCMP_ARCH_AARCH64"],
  syscalls: [
    {
      names: [
        "acct",
        "add_key",
        "bpf",
        "clock_adjtime",
        "clock_settime",
        "create_module",
        "delete_module",
        "finit_module",
        "get_mempolicy",
        "init_module",
        "ioperm",
        "iopl",
        "kcmp",
        "kexec_file_load",
        "kexec_load",
        "keyctl",
        "lookup_dcookie",
        "mbind",
        "mount",
        "move_pages",
        "name_to_handle_at",
        "open_by_handle_at",
        "perf_event_open",
        "pivot_root",
        "process_vm_readv",
        "process_vm_writev",
        "ptrace",
        "query_module",
        "quotactl",
        "reboot",
        "request_key",
        "set_mempolicy",
        "setns",
        "settimeofday",
        "stime",
        "swapon",
        "swapoff",
        "sysfs",
        "syslog",
        "umount",
        "umount2",
        "unshare",
        "uselib",
        "userfaultfd",
        "ustat",
        "vm86",
        "vm86old",
      ],
      action: "SCMP_ACT_ERRNO",
      args: [],
      comment: "",
      includes: {},
      excludes: {},
    },
  ],
});
